Homework 3.3
qqqbbb/Hogwarts pull request #1
Opened 2022-10-30 07:49 UTC by qqqbbb

2022-10-30 11:15 UTC, OlgaLugacheva requested changes

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +@RequestMapping("house")
house  так house, но почему не faculty ? ну ладно - главное - не запутаться

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/service/HouseService.java
> +        return repository.findById(id).get();
get() нужно убрать , лучше использовать orElseThrow()

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/service/StudentService.java
> +        return repository.findById(id).get();
get() нужно убрать , лучше использовать orElseThrow()

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +        if (house == null)
не может возвращенное значение при save быть null, spring нам это гарантирует в текущей версии - нужно убрать

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +        if (house == null)
не надо проверку на null, если будем бросать искоючение, то либо будет исключение либо вы все-таки его найдем

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +        if (house == null)
убрать

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +        List<House> houses = houseService.getAllHouses().stream().filter(h -> h.getColor().equals(color)).collect(Collectors.toList());
нужно перенести в сервис

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/StudentController.java
> +        List<Student> students = studentService.getAllStudents().stream().filter(s -> s.getAge() == age).collect(Collectors.toList());
перенести в сервис

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/StudentController.java
> +        if (student == null)
это убрать

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/StudentController.java
> +        if (student == null)
эту проверку тоже убрать

2022-10-30 11:15 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/controller/StudentController.java
> +        if (student == null)
эту проверку убрать

2022-10-31 04:57 UTC, qqqbbb commented on src/main/java/qqqbbb/hogwarts/school/controller/HouseController.java
> +@RequestMapping("house")
House - это из первоисточника

2022-10-31 08:39 UTC, OlgaLugacheva requested changes

2022-10-31 08:39 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/service/HouseService.java
> +        return repository.findById(id).orElseThrow();
лучше написать свое исключение и указать его

2022-10-31 08:39 UTC, OlgaLugacheva commented on src/main/java/qqqbbb/hogwarts/school/service/StudentService.java
> +        return repository.findById(id).orElseThrow();
свое исключение

2022-10-31 12:15 UTC, merged